-- Drop the Squarespace test-order flag (decided 2026-09-20).
--
-- The flag was carried over from the legacy app, where Squarespace set it on
-- orders placed against the store in test mode. Nothing here ever wrote it:
-- BigCommerce has no equivalent, so the sync relied on the DEFAULT, and the
-- only value that ever reached the column would have come from the legacy
-- import. That left a column with exactly one reader -- the `test_mode = 0`
-- clause in COUNTS_AS_MEMBERSHIP -- to describe a condition no live code path
-- can produce.
--
-- Test orders are now excluded by scripts/legacy-export/export.sql, alongside
-- the rows it already declines to export, and counted in the gap between
-- `membership_orders_total` and what it emits. Excluding them at the source
-- says the same thing in one place instead of three, and the orders never
-- enter D1 at all.
--
-- Safe as a destructive change because `membership_orders` is empty in both
-- environments: the legacy import has not been run for real yet. Had it been,
-- this would need to be a filtered rebuild rather than a DROP COLUMN.
ALTER TABLE membership_orders DROP COLUMN test_mode;
