-- Record who set a "member since" correction or a card name.
--
-- Four tables hold a decision somebody made about another person's card, and
-- until now only two of them said who made it. `revoked_cards.revoked_by` and
-- `banned_people.banned_by` were built together and got it; the two older
-- tables kept a `source` ('manual', 'admin', 'member', 'legacy_postgres') and
-- a free-text note, which says what kind of actor it was but not which one.
--
-- That is a gap in the same accountability these tables exist for. The reason
-- a revocation keeps a note is that somebody will be asked to explain the
-- decision later, and the same is true of an admin putting a different name
-- on a member's card, or moving the date the group has been told they joined.
-- A note nobody can attribute answers half the question.
--
-- `set_by` rather than a verb, because either kind of actor lands here: a
-- member editing their own card name is a `users` row too, and knowing it was
-- them rather than an admin is worth as much as the other way round.
--
-- Nullable, and not backfilled. The rows already here came from the one-time
-- legacy import or were written before this column existed, and inventing an
-- actor for them would be worse than admitting there isn't one -- the point
-- of the column is to be trustworthy.
ALTER TABLE member_since_overrides ADD COLUMN set_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE member_display_names ADD COLUMN set_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
